[config]
base_step_ms = 33.0
ui_scale_base = 1.6

[input]
move_up = "W"
move_down = "S"
move_left = "A"
move_right = "D"
zoom_in = "E"
zoom_out = "Q"
toggle_pause = "SPACE"
speed_0_5x = "DIGIT1"
speed_1x = "DIGIT2"
speed_2x = "DIGIT3"
speed_3x = "DIGIT4"
build_lumberjack = "Z"
build_house = "X"
toggle_road_mode = "R"
reset_new_seed = "T"
reset_same_seed = "N"
save_game = "F5"
load_game = "F9"
